<MyButton@Button>:
    font_size:30
    background_color:0,0,0,1
<MGL>:
    id:calculator
    display:input
    rows:5
    padding:10
    spacing:10
    canvas:
        Color:
            rgba:0.10,0,1,1
        Rectangle:
            pos:self.pos
            size:self.size
            source:"6789.jpg"
    BoxLayout:
        TextInput:
            id:input
            font_size:30
            multiline:False
    BoxLayout:
        spacing:10
        MyButton:
            text:"7"
            on_press:input.text += self.text
        MyButton:
            text:"8"
            on_press:input.text += self.text
        MyButton:
            text:"9"
            on_press:input.text += self.text
        MyButton:
            text:"("
            on_press:input.text += self.text
        MyButton:
            text:")"
            on_press:input.text += self.text
    BoxLayout:
        spacing:10
        MyButton:
            text:"4"
            on_press:input.text += self.text
        MyButton:
            text:"5"
            on_press:input.text += self.text
        MyButton:
            text:"6"
            on_press:input.text += self.text
        MyButton:
            text:"+"
            on_press:input.text += self.text
        MyButton:
            text:"-"
            on_press:input.text += self.text
    BoxLayout:
        spacing:10
        MyButton:
            text:"1"
            on_press:input.text += self.text
        MyButton:
            text:"2"
            on_press:input.text += self.text
        MyButton:
            text:"3"
            on_press:input.text += self.text
        MyButton:
            text:"%"
            on_press:input.text += self.text
        MyButton:
            text:"*"
            on_press:input.text += self.text
    BoxLayout:
        spacing:10
        MyButton:
            text:"AC"
            on_press:input.text = ""
        MyButton:
            text:"0"
            on_press:input.text += self.text
        MyButton:
            text:"."
            on_press:input.text += self.text
        MyButton:
            text:"="
            on_press:calculator.calc(input.text)
        MyButton:
            text:"/"
            on_press:input.text += self.text